const fakeData: EnergyOffer[] = [
  {
    supplierCompanyName: 'Energy Harbor LLC',
    companyName: 'Energy Harbor LLC',
    supplierAddress: '168 East Market Street',
    supplierCity: 'Akron',
    supplierState: 'OH',
    supplierZip: '44308',
    supplierPhone: '(855) 487-0822',
    supplierWebSiteUrl: 'www.energyharbor.com',
    termsOfServiceUrl: 'https://omt.energyharbor.com/Pricing/Document?productID=61364',
    signUpUrl: 'https://energyharbor.com/en/marketing-campaign-/apples-to-apples/col-ohp-24mo-offer',
    price: 0.0659,
    rateType: 'Fixed',
    renewable: 0,
    isIntroductoryOffer: false,
    termLength: 24,
    earlyTerminationFee: 0,
    monthlyFee: 0,
    isPromotionalOffer: false,
    offerDetails: 'AEP Ohio Power: Fixed price for 24 months.',
  },
  {
    supplierCompanyName: 'National Gas & Electric LLC',
    companyName: 'National Gas & Electric LLC',
    supplierAddress: '12140 Wickchester Ln',
    supplierAddress2: 'Suite 100',
    supplierCity: 'Houston',
    supplierState: 'TX',
    supplierZip: '77079',
    supplierPhone: '(888) 442-0002',
    supplierWebSiteUrl: 'www.ngande.com',
    termsOfServiceUrl: 'https://rates.ngande.com/rates/index?promocode=ohchoice',
    signUpUrl: 'https://rates.ngande.com/rates/index?promocode=ohchoice',
    price: 0.0449,
    rateType: 'Fixed',
    renewable: 100,
    isIntroductoryOffer: true,
    introductoryOfferDetails: 'New Customer Special',
    termLength: 3,
    earlyTerminationFee: 0,
    monthlyFee: 0,
    isPromotionalOffer: false,
  },
];
