// This type is the CSV Headers for the daily energy file
type RawEnergyOffer = {
  SupplierCompanyName: string,
  CompanyName: string,
  SupplierAddress: string,
  SupplierAddress2?: string,
  SupplierCity: string,
  SupplierState: string,
  SupplierZip: string,
  SupplierPhone: string,
  SupplierWebSiteUrl: string,
  TermsOfServiceURL: string,
  SignUpNowURL: string,
  Price: number,
  RateType: string,
  Renewable: number,
  IsIntroductoryOffer: string,
  IntroductoryOfferDetails?: string,
  TermLength: number,
  EarlyTerminationFee: number,
  MonthlyFee: number,
  IsPromotionalOffer: string,
  PromotionalOfferDetails?: string,
  OfferDetails?: string,
};

// What we'll output to the frontend in the response
type EnergyOffer = {
  supplierCompanyName: string,
  companyName: string,
  supplierAddress: string,
  supplierAddress2?: string,
  supplierCity: string,
  supplierState: string,
  supplierZip: string,
  supplierPhone: string,
  supplierWebSiteUrl: string,
  termsOfServiceUrl: string,
  signUpUrl: string,
  price: number,
  rateType: string,
  renewable: number,
  isIntroductoryOffer: boolean,
  introductoryOfferDetails?: string,
  termLength: number,
  earlyTerminationFee: number,
  monthlyFee: number,
  isPromotionalOffer: boolean,
  promotionalOfferDetails?: string,
  offerDetails?: string,
}
